name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER_FTP }}
          username: ${{ secrets.USERNAME_FTP }}
          password: ${{ secrets.PASSWORD_FTP }}
          local-dir: ${{ LOCAL_DIR_FTP }}
          server-dir: ${{ SERVER_DIR_FTP }}
