name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FTP
      run: sudo apt-get install -y lftp

    - name: Upload files via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
        set ssl:verify-certificate no;
        mirror -R --delete --verbose=3 dist /public_html/carmeuseColombia;
        bye
        "


