name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: sebastianpopp/ftp-action@v2
        with:
          host: ftp://grupopso.com.co
          user: u347257743.maigerprofile.com
          password: Linda4785
          local-dir: ./
          remote-dir: /public_html
